language: ruby
cache:
- bundler
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
deploy:
  provider: heroku
  api_key:
    secure: LIXWeTLrJNsf1NbV9/THUu6ra9c4xq2Z9OVjUqzMSygoE8cg/YuInoqC5hKB0YhykybhTRhjYt0Bt5LTE8obuUVqIM2OMxc8C1uX3NYn2FYcG7kk7XZUY6mT5qUpas1bjNfDT95QZcpLwJ7Mcn/CSrKwdR1K4sP7YVWgm+qyrKjTF/Ms2S0eOsEubSf3Kj8ZsKFU0wMM69x4WIl7BfjDKqiT9HW5KuIk+KzKbUCIbZ7x0/XYlEAK83V2MdNLiHb+IIdgkV6iCTRhcooh/hmWUAL8Vxu8ZDZJjfcLTBcAlyeRcjwzreUQDRM8ZovW0otiVGu5yMndZpRCgKtv8JLvF2ar6oz10nahFyqJ+LEsSMZqUXLw1tJVZSKL4GsSeoLDAMSAw4wOk7WvTlntTu4THRdwNWDyGOmo5ikhu8N1a5+4hVy9iTubGglDN/+QAaoDzdFcIS5uVNKKr3kyzXRRfYfBKyf5NZNpwBuYmsnGBB47IIPXI7YMrWmFiysDIv1b6oc8dAVKJTiW5uMbaq5lY4T3HHoNM3J+qp3EDR+cKXm2VSb5pMrHljIbvDmDIxpIEN+h/CFnm/Imi2AkMt0vAs0diBmy4k+q9R17YdN9agOpxTTxF+D5uqOtHE6sDOnAQVTMFRcL5cLcg1BwrPVt8VP5tBtGctP7E173GK2bEfk=
  app: bogeyman
  on:
    repo: diegobassan/bogeyman
  skip_cleanup: true
notifications:
  slack:
    secure: AQewopL6T/AaKBEnKMYuGvOf2sNafxqiNRVsp17Sit/gZZgo8Ctc15v6O42Bai4ei1ja7wun9smuoaLLdl9Gc2azhZORphR8bXKYw846iQNAZAXm8Uzg7vvEvetMH9yw7VhZRcnpk3eHhNuiAGRy7D94x7y4YTMHoSO0mRkwlfKN37aRyB5+JVps5d3g8nUz1fsWXPqfsFsR/qFbF8wd/xhvVlsSWrn/Nom3b9P4xTNXMG3fEIXgjnZcYyCd834emG+EbgTScY80HDUpm+CYFNhWVc65V89VQL5gJ13cKq6KVtaPVTuPzTaLZR8hqXUPjvV9nRc+PB38evBZcSmd/eqCvkjOEE1FRTMKqJw8BAa2VWYSqhJF8cTFWqBMNQz0y6cw8zewMNlQ2rJ0sbmQBIiZn3Dq0FOe3Cuecr0vGJ0qsFJA1Hbpu5Drw+OUqpP8Ig5JKKJUloPsHKh1slJfUUGK2qeB9GLqJCNnB22txrNdPWHTaCUZCOQCJhZx3NkY6UqxcrjGE9LIAr+KKTEgJkt8eu5x4yIAju+8vVG8mXNbCrhAdUuj/ifjp3CUfVL9eRzarB1Jkr0h+IYuL0JWIURIKYB81qgTwubjwRPS69IxkUxtRcsuG5fFRjPS2r5pdcld4xUbhk1QIlkhSPileajmEwD7G4G+DsoJUo9QKIs=
