language: ruby
cache:
- bundler
before_install:
  - gem update --system
  - bash -c "yes | gem uninstall -i /home/travis/.rvm/gems/ruby-2.5.0@global rake"
deploy:
  provider: heroku
  api_key:
    secure: jgU4ILeTtI9uclR63BSekZfuBN6nyuVcCkQ9DP/eR9K3JTITrPdjBvyWEM5WyVX8gkvyb7pSMKFqbwxqbfF9AFMn3FnaZ6m1TuM/WFbPEOoP9PUdCGztY0fYBY0gamQOA35f1+rho1rNYFnRX6KocWw4p6MRqU2vTyu1pgWORKVWRCUjFuyXsq5X8YNKWJlN9LzK3CZ8eHdESIdE0JrRx5aUw9Toy+tAFIz2Dom36dxgePew5E3xhxxTcqiCXHidi0DZPwS9nCpi8vK6ntLbJH13ev1mgl4bv8akb3ob8Jz9AHcXW6cB7ai1Z5yxuqHYgYShTzBkvplomPlZBjeQvI47ud/xkvySAxMk0mUlpWVlovuIeuKKkFFqpEEzMk4Z+CkN1PNK6Do3R+XHaiRec/fV4jBaA9XIPHGbHsxy+5Tof3FC/k6QNzPt/0vQZ1mccPNG2Y+ScLwqo9mps7b6Es+WS5SCnbFRGS5PII33zaAipW6IuvbxA9fWNzhSKjZwqvNQuyMrhKBx19bunaDUTVv7MOF9Q/rUv1As9zo3SXkEG9ddrnij3q/Jm1V08T+GMJH8T/RCIBVydd5GZQKpKaE/X6kKWhIz5KubbjD0cAmWdWRvTvgNqZx5mD8R9u/YuqU5Bwr6x5pT4s9lD3GuzDCt/tsVwmmukkZBqgqs8PU=
  app: bogeyman
  on:
    repo: diegobassan/bogeyman
  skip_cleanup: true
notifications:
  slack:
    secure: AQewopL6T/AaKBEnKMYuGvOf2sNafxqiNRVsp17Sit/gZZgo8Ctc15v6O42Bai4ei1ja7wun9smuoaLLdl9Gc2azhZORphR8bXKYw846iQNAZAXm8Uzg7vvEvetMH9yw7VhZRcnpk3eHhNuiAGRy7D94x7y4YTMHoSO0mRkwlfKN37aRyB5+JVps5d3g8nUz1fsWXPqfsFsR/qFbF8wd/xhvVlsSWrn/Nom3b9P4xTNXMG3fEIXgjnZcYyCd834emG+EbgTScY80HDUpm+CYFNhWVc65V89VQL5gJ13cKq6KVtaPVTuPzTaLZR8hqXUPjvV9nRc+PB38evBZcSmd/eqCvkjOEE1FRTMKqJw8BAa2VWYSqhJF8cTFWqBMNQz0y6cw8zewMNlQ2rJ0sbmQBIiZn3Dq0FOe3Cuecr0vGJ0qsFJA1Hbpu5Drw+OUqpP8Ig5JKKJUloPsHKh1slJfUUGK2qeB9GLqJCNnB22txrNdPWHTaCUZCOQCJhZx3NkY6UqxcrjGE9LIAr+KKTEgJkt8eu5x4yIAju+8vVG8mXNbCrhAdUuj/ifjp3CUfVL9eRzarB1Jkr0h+IYuL0JWIURIKYB81qgTwubjwRPS69IxkUxtRcsuG5fFRjPS2r5pdcld4xUbhk1QIlkhSPileajmEwD7G4G+DsoJUo9QKIs=
